# Generated by Django 2.2.3 on 2019-07-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='uid',
        ),
    ]
